name: mawa_package
description: A new Flutter project.
version: 0.0.3
homepage:

environment:
  sdk: ">=3.3.0 <=3.13.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  rflutter_alert: ^2.0.4
  awesome_dialog: ^3.2.1
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.3
  http: ^1.2.1
  intl: ^0.20.2
  package_info_plus: ^8.0.0
  device_info_plus: ^10.1.0
  email_validator: ^3.0.0
  another_flushbar: ^1.10.29
  permission_handler: ^10.4.5
  fluttertoast: ^8.0.9
  #  device_info: ^2.0.2
  #  geolocator: ^7.1.1
  stop_watch_timer: ^2.0.0
  dio: ^5.5.0+1
  path_provider: ^2.1.3
  device_information: ^0.0.4
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  dropdown_search: ^5.0.6
  file_picker: ^8.0.6
  flutter_animate: ^4.2.0
  ffi: ^2.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  image_path: "assets/images/appicon.png"
  android: true
  ios: true
  remove_alpha_ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
#  assets:
#    - assets/

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
